### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by dessant** [kivy-garden/garden.gauge#1]
Garden repositories must be released under the MIT license. Please tell us if you agree to release it with this license, or simply add the file, following this template: https://github.com/kivy-garden/kivy-garden.github.io/blob/master/LICENSE.

**Comment by Phisatho** [comment]
\I am not the owner of this code. It was adopted from another repository. I
believe it is stated in the code description.

If my opinion counts, I have no objection release garden.gauge under MIT
license.

Shibu Philip Thomas.

**Comment by dessant** [comment]
@Phisatho, thanks a lot, meanwhile the original author also agreed https://github.com/kivy-garden/garden.segment/issues/1#issuecomment-156188382. I'm adding the license file
