### ISSUE TITLE
Error with Scatter __init__, object.__init__() takes no parameters

### ISSUE THREAD

**Issue by PandaWhoCodes** [kivy-garden/garden.gauge#2]
super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 254, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:5332)
 TypeError: object.__init__() takes no parameters

**Comment by KeyWeeUsr** [comment]
A problem with `Scatter`'s properties, tracking at kivy/kivy#5064

**Comment by KeyWeeUsr** [comment]
fixed with 57e7339
